# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'jbumapp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for jbumapp
  pod 'Firebase/Core'
  pod 'Firebase/Analytics'
  pod 'Firebase/Crash'
  pod 'Firebase/Performance'

  target 'jbumappUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
